contextSource: env
ossBucketName: hryang-serverless
vscode:
  host: 127.0.0.1
  port: 9527
  dataDirectory: /Users/hryang/projects/serverless-webide/target/vscode-server
  binaryDirectory: /Users/hryang/Projects/serverless-webide/third_party/openvscode-server-v1.67.0-darwin-arm64/bin
  dataOssPath: tests/vscode-server/vscode-server-data.tar.gz
workspace:
  directory: /Users/hryang/projects/serverless-webide/target/workspace
  ossPath: tests/vscode-server/workspace.tar.gz
